kumuluzee:
  name: app01
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000

  discovery:
    ttl: 20
    ping-interval: 15
    
gateway:
  gateway-url: none-url

  